# Generated by Django 6.0.7 on 2026-07-23 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_academy_student_coach_student_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='scholarship_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Scholarship discount percentage (0-100)', max_digits=5),
        ),
    ]
