# Generated by Django 6.0.7 on 2026-07-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatchRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateField()),
                ('opponent', models.CharField(max_length=200)),
                ('runs', models.IntegerField(default=0)),
                ('wickets', models.IntegerField(default=0)),
                ('catches', models.IntegerField(default=0)),
                ('strike_rate', models.FloatField(default=0)),
                ('economy', models.FloatField(default=0)),
                ('result', models.CharField(choices=[('Win', 'Win'), ('Loss', 'Loss'), ('Draw', 'Draw'), ('Cancelled', 'Cancelled')], max_length=20)),
                ('is_man_of_the_match', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-match_date'],
            },
        ),
    ]
