# Generated by Django 6.0.7 on 2026-07-23 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_matchrecord_academy_matchrecord_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchrecord',
            name='venue',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
