# Generated by Django 6.0.7 on 2026-07-21 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('batting_rating', models.IntegerField(default=5)),
                ('bowling_rating', models.IntegerField(default=5)),
                ('fielding_rating', models.IntegerField(default=5)),
                ('fitness_rating', models.IntegerField(default=5)),
                ('discipline_rating', models.IntegerField(default=5)),
                ('coach_remarks', models.TextField(blank=True)),
                ('overall_rating', models.FloatField(default=5, editable=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='students.student')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
